articles/urls.py
from django.urls import path
from articles.views import ArticleView, CategoryView

app_name = 'articles'
urlpatterns = [
    path('categories/<slug:category_slug>/', CategoryView.as_view(), name='category_read'),
    path('<slug:article_slug>/', ArticleView.as_view(), name='article_read'),
]

authnapp/urls.py
from django.urls import path

import authnapp.views as authnapp
from authnapp.apps import AuthnappConfig

app_name = AuthnappConfig.name

urlpatterns = [
    path("login/", authnapp.login, name="login"),
    path("logout/", authnapp.logout, name="logout"),
]

habr/urls.py
from django.contrib import admin
from django.urls import path, include

from articles.views import MainView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", MainView.as_view(), name="index"),
    path("articles/", include("articles.urls", namespace="articles")),
    path("auth/", include("authnapp.urls", namespace="auth")),
]

articles/models.py
"""
Stores the user, article, category and tag models.
"""

from datetime import datetime
from django.db import models
from userapp.models import HabrUser

class Category(models.Model):
    """The model for the category."""
    category_name = models.CharField(max_length=128)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    is_active = models.BooleanField(verbose_name="раздел активен", default=True, db_index=True)

    def __str__(self):
        """Forms a printable representation of the object.
        Returns the name of the category.
        """
        return str(self.category_name)

    class Meta:
        """Ordering categories according to their id.
        """
        ordering = ('id',)
        verbose_name = 'Раздел сайта'
        verbose_name_plural = 'Разделы сайта'




class Tag(models.Model):
    """The model for the tag."""
    tag_name = models.CharField(verbose_name="наименование", max_length=128, blank=False)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    def __str__(self):
        """Forms a printable representation of the object.
        Returns the name of the tag.
        """
        return str(self.tag_name)

    class Meta:
        """Ordering users according to their id.
        """
        ordering = ('tag_name',)
        verbose_name = 'Теги'
        verbose_name_plural = 'Тег'


class Article(models.Model):
    """The model for the article."""
    registration_time = models.DateTimeField(verbose_name="время создания", default=datetime.now)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    is_active = models.BooleanField(verbose_name="статья активна", default=False, db_index=True)
    title = models.CharField(verbose_name="заголовок", max_length=128, blank=False)
    body = models.CharField(verbose_name="тело", max_length=100000, blank=False)
    tag = models.ManyToManyField(Tag)
    user = models.ForeignKey(HabrUser, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

    def __str__(self):
        """Forms a printable representation of the object.
        Returns the title of the article.
        """
        return str(self.title)

    class Meta:
        """Ordering articles according to their date of addition (the most recent ones first).
        """
        ordering = ['-registration_time', ]
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

authnapp/models.py
from django.db import models

# Create your models here.

userapp/models.py
from django.db import models
from uuid import uuid4
from django.contrib.auth.models import AbstractUser
from datetime import datetime, timedelta

class HabrUser(AbstractUser):
    """The model for the user."""
    uuid = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    username = models.CharField(verbose_name="логин", max_length=128, blank=False, unique=True)
    first_name = models.CharField(verbose_name="имя", max_length=128, blank=False)
    last_name = models.CharField(verbose_name="фамилия", max_length=128, blank=False)
    avatar = models.ImageField(upload_to="users_avatars", blank=True)
    email = models.CharField(verbose_name="email", max_length=128, unique=True, blank=False)
    age = models.PositiveIntegerField(verbose_name="возраст", default=18)
    registration_time = models.DateTimeField(verbose_name="время регистрации", default=datetime.now)
    is_active = models.BooleanField(verbose_name="пользователь активен", default=True, db_index=True)
    activation_key = models.CharField(verbose_name="ключ подтверждения", max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(verbose_name="актуальность ключа",
                                                  default=datetime.now() + timedelta(hours=48))
    banned_until = models.DateTimeField(verbose_name="забанен до", blank=True, null=True)

    def __str__(self):
        """Forms a printable representation of the object.
        Returns the username of the user.
        """
        return str(self.username)

    class Meta:
        """Ordering users according to their id.
        """
        ordering = ('uuid',)
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

authnapp/forms.py
from django.contrib.auth.forms import AuthenticationForm
from userapp.models import HabrUser


class HabrUserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(HabrUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = HabrUser
        fields = ("username", "password")

articles/views.py
from django.db.models import Q
from django.views.generic import ListView, DetailView

from articles.models import Article, Category


class MainView(ListView):
    """View for the main page."""
    model = Article
    template_name = 'articles/index.html'
    context_object_name = 'all_articles'
    paginate_by = 3

    def get_queryset(self):
        """Displaying all active articles.
         Articles are displayed in an orderly manner, starting from the most recent."""
        return Article.objects.filter(is_active=True)


class CategoryView(ListView):
    """View for articles of a separate category (section)."""
    model = Article
    template_name = 'articles/read_category.html'
    context_object_name = 'category_articles'
    paginate_by = 3
    slug_url_kwarg = 'category_slug'
    category = ''

    def get_queryset(self):
        """Returns a queryset of active articles of the specified category."""
        self.category = Category.objects.get(slug=self.kwargs.get('category_slug'))
        return Article.objects.filter(Q(category=self.category), Q(is_active=True))

    def get_context_data(self, *args, **kwargs):
        """Puts the title in the context according to the selected category."""
        context = super().get_context_data(**kwargs)
        context['title'] = f'Посты категории {self.category}'
        return context


class ArticleView(DetailView):
    """View for the output of a separate article."""
    model = Article
    template_name = 'articles/read-article.html'
    slug_url_kwarg = 'article_slug'

authnapp/views.py
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse

from authnapp.forms import HabrUserLoginForm


def login(request):
    title = "Вход в систему"

    login_form = HabrUserLoginForm(data=request.POST or None)

    if request.method == "POST" and login_form.is_valid():
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(username=username, password=password)
        if user and user.is_active:
            auth_login(request, user)
            return HttpResponseRedirect(reverse("index"))

    content = {"title": title, "login_form": login_form}
    return render(request, "authnapp/login.html", content)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("index"))

userapp/views.py
from django.shortcuts import render

# Create your views here.

articles/templates/articles/base.html
{% load static %}
{% load custom_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/habr.css' %}" rel="stylesheet"/>
</head>

<body class="sb-nav-fixed">

<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand grey" href="{% url 'index' %}">Главная</a>
    <button class="btn btn-link btn-md m-2 order-1 order-lg-0 btn-grey blacked" id="sidebarToggle"><i
            class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0
    mr-md-3 my-2 my-md-0" action="#">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск по статьям"
                   name="search_panel" aria-label="Search" aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit"><i class="fas fa-search grey"></i></button>
            </div>
        </div>
    </form>

    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle rounded btn-grey blacked" id="userDropdown" role="button"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw blacked"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                {% include 'authnapp/includes/inc_user_auth.html' %}
                <!-- Задел для будущего выпадающего меню авторизации -->
                {#                {% if user.is_authenticated %}#}
                {#                    <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти из профиля</a>#}
                {#                {% else %}#}
                {#                    <a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a>#}
                {#                    <a class="dropdown-item" href="{% url 'users:login' %}">Авторизация</a>#}
                {#                {% endif %}#}

            </div>
        </li>
    </ul>
</nav>

<div id="layoutSidenav">

<!-- Пункты меню (использован templatetag) -->
{% show_categories %}

<!-- Основное содержимое страницы подгружаем сюда -->
    {% block content %}
    {% endblock %}
</div>


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<script src="https://kit.fontawesome.com/2b537a4c3e.js" crossorigin="anonymous"></script>
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>

</body>
</html>

articles/templates/articles/includes/footer.html
<footer class="bg-dark navbar-fixed-bottom">
    <div class="container">
        <p class="text-center text-white">Copyright &copy; Команда 3 2022 Выпускной проект</p>
    </div>
</footer>

articles/templates/articles/includes/menu.html
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Разделы</div>

                {% for item in category_menu_items %}
                <a class="nav-link" href="{% url 'articles:category_read' item.slug %}">
                    <div class="menu-font">{{ item.category_name }}</div>
                </a>
                {% endfor %}

                <!-- Задел для будущего пункта меню Мой профиль -->
                {#                    {% if user.is_authenticated %}#}
                {#                        <a class="nav-link" href="{% url 'users:profile' %}">#}
                {#                            <div class="sb-nav-link-icon">#}
                {#                                <i class="fa fa-user grey"></i>#}
                {#                            </div>#}
                {#                            Мой профиль#}
                {#                        </a>#}
                {#                        <a id="my_profile"></a>#}
                {#                    {% else %}#}
                {#                        <a class="nav-link" href="{% url 'users:login' %}">#}
                {#                            <div class="sb-nav-link-icon">#}
                {#                                <i class="fa fa-user grey"></i>#}
                {#                            </div>#}
                {#                            Авторизация на сайте#}
                {#                        </a>#}
                {#                    {% endif %}#}

                <input type="button" class="btn btn-block btn-grey"
                       onclick="window.location.href = 'http://127.0.0.1:8000/admin';"
                       value="К админке"/>

                <!-- Задел для будущего пункта меню перехода к админке -->
                {#                    {% if user.is_staff %}#}
                {#                        <input type="button" class="btn btn-block btn-grey blacked"#}
                {#                               onclick="window.location.href = '#';"#}
                {#                               value="К админке"/>#}
                {#                    {% endif %}#}

                <button onClick="javascript:history.go(-1);" type="submit" class="btn btn-block btn-grey blacked">
                    <i class="fa fa-undo"></i> Назад
                </button>
            </div>

        </div>
        <div class="sb-sidenav-footer"></div>
    </nav>
</div>

articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% load static %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid text-center">
                <h1 class="mt-4 mb-4">Свежие статьи</h1>

                {% for article in all_articles %}

                    <div class="row main p-3 border border-grey mt-1">
                        <div class="col-3">

                            <div>
                                <div class="col-12 row border">
                                    <p>Добавлена: {{ article.registration_time | date }}</p>
                                </div>
                                <div class="col-12 row border">
                                    <p> Категория: <strong>{{ article.category }}</strong></p>
                                </div>
                            </div>

                        </div>
                        <div class="col-9 mt-3 underlined">
                            <h3>{{ article.title }}</h3>
                        </div>

                        <div class="col-12 mt-5">
                            {{ article.body |truncatechars:350 }}
                        </div>
                        <div class="col-12 text-right">
                            <a href="{% url 'articles:article_read' article.slug %}"
                       class="admin-link">Читать статью</a>
                        </div>
                    </div>
                {% endfor %}

                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                            <a class="page-link font-xl {% if page_obj.has_previous %} grey {% endif %}"
                               href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }}
                               {% else %} # {% endif %}"
                               tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        {% for page in page_obj.paginator.page_range %}
                            <li class="page-item"><a class="page-link grey menu-font"
                                                     href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}
                        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                            <a class="page-link menu-font {% if page_obj.has_next %} grey {% endif %}"
                               href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }}
                                     {% else %} # {% endif %}">Next</a>
                        </li>
                    </ul>
                </nav>

            </div>
        </main>
        {% include 'articles/includes/footer.html' %}
    </div>
{% endblock %}

articles/templates/articles/read-article.html
{% extends 'articles/base.html' %}
{% load static %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid text-center">
                <div class="row main p-3 mt-1">
                    <div class="col-4">

                        <div class="text-left">
                            <div class="col-12 row border">
                                <p>Добавлена: {{ article.registration_time | date }}</p>
                            </div>
                            <div class="col-12 row border">
                                <p> Категория: <strong>{{ article.category }}</strong></p>
                            </div>
                            <div class="col-12 row border">
                                <p> Автор: {{ article.user }}</p>
                            </div>
                        </div>

                    </div>
                    <div class="col-8 mt-3 underlined">
                        <h4>{{ article.title }}</h4>
                    </div>

                    <div class="col-12 mt-5 menu-font text-left">
                            {{ article.body }}
                    </div>

                    <div class="col-12 mt-1 text-right">
                        <hr>
                        Теги:
                        {% for tag in article.tag.all %}
                            <u><a href="#">{{ tag }}</a></u>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-6">
                        <a class='btn btn-outline-dark btn-grey btn-block ml-3 mr-1 mb-1'
                           href='{% url 'articles:category_read' article.category.slug %}'>К статьям категории {{ article.category }}</a>
                    </div>
                    <div class="col-6">
                        <a class='btn btn-outline-dark btn-grey btn-block ml-3 mr-1 mb-1'
                           href='{% url 'index' %}'>На главную</a>
                    </div>
                </div>
            </div>
        </main>
        {% include 'articles/includes/footer.html' %}
    </div>
{% endblock %}

articles/templates/articles/read_category.html
{% extends 'articles/base.html' %}
{% load static %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid text-center">
                <h2 class="mt-4 mb-4">{{ title }}</h2>

                {% for article in category_articles %}

                    <div class="row main p-3 border border-grey mt-1 mb-1">
                        <div class="col-4">

                            <div class="text-left">
                                <div class="col-12 row border">
                                    <p>Добавлена: {{ article.registration_time | date }}</p>
                                </div>
                                <div class="col-12 row border">
                                    <p>Автор: <strong>{{ article.user }}</strong></p>
                                </div>
                            </div>

                        </div>
                        <div class="col-8 mt-3 underlined">
                            <h4>{{ article.title }}</h4>
                        </div>

                        <div class="col-12 mt-5 text-left">
                            {{ article.body |truncatechars:350 }}
                        </div>
                        <div class="col-12 text-right">
                            <a class="btn btn-sm btn-outline-dark rounded-3 btn-grey" href="{% url 'articles:article_read' article.slug %}">Читать статью</a>
                        </div>
                    </div>

                {% empty %}
                    <div class="row main p-3 border border-grey mt-1 mb-1">
                        <div class="col-12 text-center">
                            К сожалению, в данной категории пока нет статей
                        </div>
                    </div>

                {% endfor %}

                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                            <a class="page-link menu-font btn btn-sm btn-outline-dark rounded-3
                            {% if page_obj.has_previous %} btn-grey dark-grey {% else %} btn-grey-disabled {% endif %}"
                            href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }}
                            {% else %} # {% endif %}"
                            tabindex="-1" aria-disabled="true"><i class="fas fa-backward"></i></a>
                        </li>
                        {% for page in page_obj.paginator.page_range %}
                            <li class="page-item">
                                <a class="page-link menu-font btn btn-sm btn-outline-dark rounded-3 btn-grey dark-grey"
                                href="?page={{ page }}">{{ page }}</a>
                            </li>
                        {% endfor %}
                        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                            <a class="page-link menu-font btn btn-sm btn-outline-dark rounded-3
                            {% if page_obj.has_next %} btn-grey dark-grey {% else %} btn-grey-disabled {% endif %}"
                               href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }}
                               {% else %} # {% endif %}"><i class="fas fa-forward"></i></a>
                        </li>
                    </ul>
                </nav>

            </div>
        </main>
        {% include 'articles/includes/footer.html' %}
    </div>
{% endblock %}

authnapp/templates/authnapp/includes/inc_user_auth.html
{% if request.user.is_authenticated %}
    <a class="dropdown-item" href="{% url 'auth:login' %}">{{ user.username|default:'Пользователь' }}</a>
    <a class="dropdown-item" href="{% url 'auth:logout' %}">Выйти из профиля</a>
{% else %}
    <a class="dropdown-item" href="{% url 'auth:login' %}">Войти в профиль</a>
{% endif %}

authnapp/templates/authnapp/login.html
{% extends 'articles/base.html' %}
{% load static %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid text-center">
            <h2 class="mt-4 mb-4">{{ title }}</h2>
            <div class="login">
                <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
                    {% csrf_token %}
                    {{ login_form.as_p }}
                    <br>
                    <input class="form-control" type="submit" value="войти">
                </form>
            </div>
        </div>
    </main>
    {% include 'articles/includes/footer.html' %}
</div>
{% endblock %}